# Generated by Django 3.2 on 2021-06-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='modo_escuro',
            field=models.BooleanField(default=False, verbose_name='ativar modo escuro'),
        ),
    ]
