# Generated by Django 3.2 on 2021-05-06 19:54

from django.db import migrations


class Migration(migrations.Migration):
	initial = False

	dependencies = [
		('questionarios', '0001_initial'),
	]

	operations = [
		migrations.RunSQL(
			'''
			DROP VIEW IF EXISTS core_ranks;
			CREATE OR REPLACE VIEW core_ranks AS
				select row_number() over() as id,
				z.*
				from (
				select bs.*,
				row_number() over (partition by bs.empresa order by bs.pontuacao desc, bs.data_ultima_prova) posicao
				from (
				select e.nome as empresa,
				b.username as usuario,
				b.first_name || ' ' || b.last_name as nome,
				d.foto_perfil as avatar,
				sum((case when a.e_correta = true then 1 else 0 end)) qtd_acertos,
				count(a.e_correta) qtd_perguntas,
				max(a.criado_em) data_ultima_prova,
				(cast(sum((case when a.e_correta = true then 1 else 0 end)) as float) / cast(count(a.e_correta) as float)) * 10 pontuacao
				from questionarios_avaliacao a
				inner join auth_user b on a.criado_por_id = b.id
				inner join cursos_curso c on a.curso_id = c.id
				inner join alunos_aluno d on a.criado_por_id = d.usuario_id
				inner join empresas_empresa e on d.empresa_id = e.id
				group by e.nome,
				b.username,
				b.first_name || ' ' || b.last_name,
				d.foto_perfil
				) bs
				) z 
				; 
			'''
		),
		migrations.RunSQL(
			'''
			DROP VIEW IF EXISTS core_ranks_curso;
			CREATE OR REPLACE VIEW core_ranks_curso AS
				select row_number() over() as id,
				z.*
				from (
				select bs.*,
				row_number() over (partition by bs.empresa, bs.nome_curso order by bs.pontuacao desc, bs.data_ultima_prova) posicao
				from (
				select e.nome as empresa,
				c.nome as nome_curso,
				b.username as usuario,
				b.first_name || ' ' || b.last_name as nome,
				d.foto_perfil as avatar,
				sum((case when a.e_correta = true then 1 else 0 end)) qtd_acertos,
				count(a.e_correta) qtd_perguntas,
				max(a.criado_em) data_ultima_prova,
				(cast(sum((case when a.e_correta = true then 1 else 0 end)) as float) / cast(count(a.e_correta) as float)) * 10 pontuacao
				from questionarios_avaliacao a
				inner join auth_user b on a.criado_por_id = b.id
				inner join cursos_curso c on a.curso_id = c.id
				inner join alunos_aluno d on a.criado_por_id = d.usuario_id
				inner join empresas_empresa e on d.empresa_id = e.id
				group by e.nome,
				c.nome,
				b.username,
				b.first_name || ' ' || b.last_name,
				d.foto_perfil
				) bs
				) z
				; 
			'''
		),
	]
