# Generated by Django 3.2 on 2021-06-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_preferencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preferencia',
        ),
    ]
