# Generated by Django 3.2 on 2021-06-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='conteudo',
            field=models.CharField(blank=True, help_text='Um resumo do material (Não é obrigatório)', max_length=200),
        ),
    ]
