# Generated by Django 3.2 on 2021-06-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0002_alter_material_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='arquivo',
            field=models.FileField(default=1, upload_to='material'),
            preserve_default=False,
        ),
    ]
