# Generated by Django 3.2 on 2021-05-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20210513_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='categoria'),
        ),
    ]
