# Generated by Django 3.2 on 2021-07-17 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_aula_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topico',
            options={'ordering': ['curso_id', 'numero'], 'verbose_name': 'Tópico', 'verbose_name_plural': 'Tópicos'},
        ),
    ]
