# Generated by Django 3.2 on 2021-05-11 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField(help_text='Digite a pergunta.', unique=True, verbose_name='Pergunta')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_pergunta_criadopor', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_pergunta_modificadopor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('observacao', models.CharField(blank=True, max_length=250, null=True, verbose_name='Observação')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_questionario_criadopor', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(help_text='Selecione o curso do qual deseja criar o questionário', on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_curso', to='cursos.curso')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_questionario_modificadopor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionários',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('resposta', models.CharField(help_text='Digite as opções de resposta das perguntas.', max_length=200)),
                ('e_correta', models.BooleanField(default=False, help_text='Marque esse campo, somente se essa opção for a resposta certa da pergunta.')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_resposta_criadopor', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_resposta_modificadopor', to=settings.AUTH_USER_MODEL)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_pergunta', to='questionarios.pergunta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_prova_criadopor', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(help_text='Informação atribuída automaticamente.', on_delete=django.db.models.deletion.CASCADE, related_name='questionario_curso', to='cursos.curso')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_matricula', to='cursos.matricula')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_prova_modificadopor', to=settings.AUTH_USER_MODEL)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_prova', to='questionarios.questionario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('e_correta', models.BooleanField(default=False)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_avaliacao_criadopor', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prova_curso', to='cursos.curso')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_avaliacao_modificadopor', to=settings.AUTH_USER_MODEL)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prova_perguntas', to='questionarios.pergunta')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prova_aluno', to='questionarios.prova')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prova_respostas', to='questionarios.resposta')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='QuestionarioXPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_questionarioxpergunta_criadopor', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_questionarioxpergunta_modificadopor', to=settings.AUTH_USER_MODEL)),
                ('pergunta', models.ForeignKey(help_text='Selecione uma das perguntas cadastradas em nosso banco de dados, ou clique no + ao lado para adiconar uma nova pergunta.', on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_mapeadas', to='questionarios.pergunta')),
                ('questionario', models.ForeignKey(help_text='Para adicionar uma pergunta a um Questionário existente, selecione pelo nome do curso. Caso queira montar um novo questionário, cliqueo no botão + ao lado.', on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_mapeados', to='questionarios.questionario', verbose_name='Questionário do curso')),
            ],
            options={
                'verbose_name': 'Mapeamento de Questionário e Perguntas',
                'verbose_name_plural': 'Mapeamento de Questionários e Perguntas',
                'unique_together': {('questionario', 'pergunta')},
            },
        ),
    ]
