# Generated by Django 3.2 on 2021-06-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='tentativa',
            field=models.IntegerField(default=1),
        ),
    ]
