# Generated by Django 3.2 on 2021-05-11 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('mensagem', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='notificacoes')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_notificacao_criadopor', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_notificacao_modificadopor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='NotificacaoDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('is_empresa', models.BooleanField(default=False, verbose_name='Para Empresa?')),
                ('is_curso', models.BooleanField(default=False, verbose_name='Para Curso?')),
                ('is_usuario', models.BooleanField(default=False, verbose_name='Para Usuário?')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_curso', to='cursos.curso')),
                ('destinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_destinarios', to=settings.AUTH_USER_MODEL, verbose_name='destinário')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_empresa', to='empresas.empresa')),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_destinario', to='notificacoes.notificacao')),
            ],
            options={
                'verbose_name': 'Destinatário Notificação',
                'verbose_name_plural': 'Destinatários Notificações',
            },
        ),
        migrations.CreateModel(
            name='NotificacaoEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('lida', models.BooleanField(default=False, verbose_name='Foi lida?')),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('notificacao_destinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_enviadas', to='notificacoes.notificacaodestinatario')),
            ],
            options={
                'verbose_name': 'Notificação Enviada',
                'verbose_name_plural': 'Notificações Enviadas',
            },
        ),
    ]
